### ISSUE TITLE
plesk 12 has changed log paths

### ISSUE THREAD

**Issue by tmuka** [uuf6429/httpdmon#10]
Thanks for the great tool!  On my Ubuntu 14/Plesk 12 server the log paths were as follows.  I added the to the list and am good to go.

 '/var/www/vhosts/*/logs/access_log',                             // linux + plesk 12
 '/var/www/vhosts/*/logs/error_log',                              // linux + plesk 12

It's worth noting that Plesk 12 also makes duplicate copies of the logs with different permissions to /var/www/vhosts/system/*/logs/(access_log|error_log), but they don't show correct associated domain name when that path is used in httpdmon.

I don't know if it's worth including the new paths in the tool or not, but hope this helps somebody else!

**Comment by uuf6429** [comment]
Thanks for the report Tony!
I've applied the fix as per your suggestion.

**Comment by tmuka** [comment]
Great!
